"""Write data/clans.json: territories of local elite groups (地方豪族/士人集团): aristocratic clans, regional power blocs,
military cliques, court factions and merchant guilds, each with the years it mattered and its home commanderies.
Drafted from general knowledge (AI-written, not source-checked): years are approximate, and the area is a soft blob
around the home seats (郡望/籍贯), not a real border.
Fields: id, name/name_zh, kind (gentry | bloc | military | faction | merchant), from/to, seats [[lon, lat, place_zh]],
families/families_zh, people/people_zh, summary/summary_zh, source, geometry (MultiPolygon)."""
import json, math
from shapely.geometry import MultiPoint, mapping
from shapely.ops import unary_union

G = [
 dict(id="fengpei", name="Feng-Pei Clique", name_zh="丰沛集团", kind="bloc", from_=-209, to=-157,
      seats=[(116.6, 34.7, "丰"), (116.94, 34.72, "沛"), (116.35, 34.43, "砀"), (116.94, 34.18, "萧")],
      families="Liu Bang's hometown followers", families_zh="刘邦同乡故旧",
      people="Xiao He, Cao Can, Zhou Bo, Fan Kuai, Xiahou Ying", people_zh="萧何、曹参、周勃、樊哙、夏侯婴",
      summary="Liu Bang's neighbours from Feng and Pei rose with him and became the marquises and chancellors of early Han; their grip on court lasted until Emperor Wen's reign.",
      summary_zh="刘邦起兵时的丰、沛同乡，入汉后封侯拜相，汉初丞相多出其中，直到文帝时才逐渐让位于新人。",
      source="https://zh.wikipedia.org/wiki/丰沛集团"),
 dict(id="nanyang", name="Nanyang Magnates", name_zh="南阳豪族", kind="bloc", from_=22, to=125,
      seats=[(112.53, 33.0, "宛"), (112.36, 32.52, "新野"), (112.75, 32.13, "蔡阳")],
      families="Liu, Deng, Yin, Li", families_zh="刘、邓、阴、李",
      people="Liu Xiu, Deng Yu, Li Tong, Yin Shi", people_zh="刘秀、邓禹、李通、阴识",
      summary="Landed families of Nanyang backed Liu Xiu's rising; they filled the Cloud Terrace generals and supplied Eastern Han's empresses (Yin, Deng).",
      summary_zh="南阳豪强地主支持刘秀起兵，云台诸将多出于此，阴、邓等家族又世代出皇后外戚。",
      source="https://zh.wikipedia.org/wiki/云台二十八将"),
 dict(id="hebei-han", name="Hebei Magnates", name_zh="河北豪族", kind="bloc", from_=23, to=60,
      seats=[(114.57, 38.15, "真定"), (115.5, 40.4, "上谷"), (116.8, 40.4, "渔阳"), (115.56, 37.6, "信都")],
      families="Geng of Shanggu, Liu Yang of Zhending, Guo", families_zh="上谷耿氏、真定刘杨、郭氏",
      people="Geng Yan, Kou Xun, Liu Zhi, Empress Guo Shengtong", people_zh="耿弇、寇恂、刘植、郭圣通",
      summary="Hebei clans and their cavalry gave Liu Xiu the army to win the empire; Liu married into the Zhending royal house to secure them.",
      summary_zh="河北豪族与幽州突骑为刘秀提供了争天下的本钱，刘秀娶真定郭圣通以结好真定王刘杨。",
      source="https://zh.wikipedia.org/wiki/郭圣通"),
 dict(id="liangzhou", name="Liang Province Generals", name_zh="凉州集团", kind="military", from_=160, to=200,
      seats=[(102.63, 37.93, "武威"), (106.7, 35.5, "安定"), (103.85, 35.37, "陇西"), (103.8, 36.06, "金城")],
      families="Frontier families of the northwest", families_zh="西北边地将门",
      people="Huangfu Gui, Zhang Huan, Duan Jiong, Dong Zhuo", people_zh="皇甫规、张奂、段颎、董卓",
      summary="Hardened by wars with the Qiang, northwestern commanders formed their own power; Dong Zhuo led them into Luoyang in 189 and broke the Han court.",
      summary_zh="与羌人长期作战的西北将领自成一系（凉州三明），189年董卓率凉州兵入洛阳，东汉朝廷由此崩坏。",
      source="https://zh.wikipedia.org/wiki/凉州三明"),
 dict(id="ruying", name="Ru-Ying Scholars", name_zh="汝颍士人", kind="gentry", from_=150, to=260,
      seats=[(113.8, 34.0, "许"), (113.85, 34.03, "颍阴"), (113.47, 34.15, "阳翟"), (114.6, 32.95, "平舆"), (114.5, 33.3, "汝阳")],
      families="Xun, Chen, Zhong of Yingchuan; Yuan of Runan", families_zh="颍川荀、陈、钟，汝南袁",
      people="Xun Yu, Chen Qun, Zhong Yao, Guo Jia, Yuan Shao", people_zh="荀彧、陈群、钟繇、郭嘉、袁绍",
      summary="Learned clans of Runan and Yingchuan led Han scholarly opinion; they staffed Cao Cao's government and Chen Qun's nine-rank system kept power with such families.",
      summary_zh="汝南、颍川名士主导东汉清议，后多为曹操谋臣；陈群创九品中正制，使仕途为世家所据。",
      source="https://zh.wikipedia.org/wiki/颍川荀氏"),
 dict(id="qiaopei", name="Qiao-Pei Clique", name_zh="谯沛集团", kind="military", from_=190, to=249,
      seats=[(115.78, 33.85, "谯"), (116.8, 33.95, "沛国")],
      families="Cao and Xiahou", families_zh="曹氏、夏侯氏",
      people="Cao Ren, Xiahou Dun, Xiahou Yuan, Cao Shuang", people_zh="曹仁、夏侯惇、夏侯渊、曹爽",
      summary="Cao Cao's kinsmen from Qiao held Wei's armies; Sima Yi's coup of 249 against Cao Shuang ended their power.",
      summary_zh="曹操宗族与同乡掌握曹魏兵权，249年司马懿发动高平陵之变诛曹爽，谯沛集团就此失势。",
      source="https://zh.wikipedia.org/wiki/高平陵之变"),
 dict(id="huaisi", name="Huai-Si Clique", name_zh="淮泗集团", kind="bloc", from_=194, to=230,
      seats=[(117.0, 31.4, "舒"), (118.0, 32.6, "东城"), (117.2, 34.26, "彭城"), (119.4, 32.4, "广陵")],
      families="Northern émigrés serving the Sun", families_zh="渡江投奔孙氏的江北士人",
      people="Zhou Yu, Lu Su, Zhang Zhao, Lü Meng", people_zh="周瑜、鲁肃、张昭、吕蒙",
      summary="Men from north of the Yangtze who crossed with Sun Ce formed Wu's first generation of commanders and ministers.",
      summary_zh="随孙策渡江的淮泗人士，构成孙吴第一代将帅与重臣，此后逐渐让位于江东大族。",
      source="https://zh.wikipedia.org/wiki/淮泗集团"),
 dict(id="wusi", name="Four Clans of Wu", name_zh="江东大族", kind="gentry", from_=200, to=618,
      seats=[(120.6, 31.3, "吴"), (120.58, 30.0, "会稽"), (120.1, 30.87, "吴兴"), (119.8, 31.36, "义兴")],
      families="Gu, Lu, Zhu, Zhang of Wu; Yu, Wei, Kong, He of Kuaiji", families_zh="吴郡顾陆朱张，会稽虞魏孔贺",
      people="Lu Xun, Lu Kang, Gu Yong, Lu Ji", people_zh="陆逊、陆抗、顾雍、陆机",
      summary="The native southern gentry: pillars of Wu, then second to the northern émigré clans under Eastern Jin and the Southern Dynasties.",
      summary_zh="江东本土士族（吴姓），孙吴的柱石；东晋南朝时地位次于南渡的侨姓门阀。",
      source="https://zh.wikipedia.org/wiki/吴郡四姓"),
 dict(id="jingzhou-shu", name="Jing Province Faction", name_zh="荆州集团", kind="bloc", from_=209, to=263,
      seats=[(112.14, 32.0, "襄阳"), (112.2, 30.35, "江陵"), (111.6, 26.2, "零陵"), (112.5, 27.73, "湘乡")],
      families="Jingzhou scholars who followed Liu Bei", families_zh="随刘备入蜀的荆州士人",
      people="Zhuge Liang, Pang Tong, Ma Liang, Jiang Wan, Fei Yi", people_zh="诸葛亮、庞统、马良、蒋琬、费祎",
      summary="Liu Bei's followers from Jingzhou ran Shu-Han after 214, ahead of the earlier migrants (Dongzhou) and the native Yizhou gentry.",
      summary_zh="刘备的荆州班底入蜀后掌握蜀汉中枢，地位高于刘璋旧部的东州士人与益州本土士人。",
      source="https://zh.wikipedia.org/wiki/蜀汉"),
 dict(id="yizhou", name="Native Yizhou Gentry", name_zh="益州本土士人", kind="gentry", from_=194, to=263,
      seats=[(104.07, 30.66, "成都"), (106.0, 31.58, "巴西"), (104.3, 31.0, "广汉"), (104.0, 29.6, "犍为")],
      families="Qiao, Du, Zhang, Huang of Ba and Shu", families_zh="巴蜀谯、杜、张、黄诸姓",
      people="Qiao Zhou, Du Qiong, Zhang Yi, Huang Quan", people_zh="谯周、杜琼、张裔、黄权",
      summary="Local Sichuan gentry, kept from the top under Liu Zhang and Liu Bei; in 263 Qiao Zhou argued for surrender to Wei.",
      summary_zh="巴蜀本地士族，在刘璋、刘备时代都未居要津；263年谯周力主降魏。",
      source="https://zh.wikipedia.org/wiki/谯周"),
 dict(id="qiaoxing", name="Émigré Great Clans", name_zh="侨姓门阀", kind="gentry", from_=317, to=589,
      seats=[(118.8, 32.05, "建康"), (120.85, 29.9, "始宁"), (119.45, 32.2, "京口"), (120.58, 30.0, "山阴")],
      families="Wang of Langya, Xie of Chenjun, Yu of Yingchuan, Huan of Qiao", families_zh="琅琊王氏、陈郡谢氏、颍川庾氏、谯国桓氏",
      people="Wang Dao, Xie An, Yu Liang, Huan Wen, Wang Xizhi", people_zh="王导、谢安、庾亮、桓温、王羲之",
      summary="Northern clans that fled south in 317 settled around Jiankang and Kuaiji; 'Wang and Ma share the realm' — they shared power with the Jin throne.",
      summary_zh="永嘉之乱后南渡的北方大族聚居建康、会稽一带，“王与马，共天下”，与东晋皇室共掌朝政。郡望仍称北方原籍。",
      source="https://zh.wikipedia.org/wiki/门阀政治"),
 dict(id="beifu", name="Northern Garrison Army", name_zh="北府兵集团", kind="military", from_=377, to=420,
      seats=[(119.45, 32.2, "京口"), (119.4, 32.4, "广陵"), (119.95, 31.78, "晋陵")],
      families="Northern refugee soldiers", families_zh="南渡流民武装",
      people="Xie Xuan, Liu Laozhi, Liu Yu", people_zh="谢玄、刘牢之、刘裕",
      summary="Xie Xuan raised refugee soldiers at Jingkou; they won at the Fei River in 383, and Liu Yu used them to end Jin and found the Song.",
      summary_zh="谢玄在京口招募流民组建，383年淝水之战大胜前秦；刘裕凭借北府兵代晋建宋。",
      source="https://zh.wikipedia.org/wiki/北府兵"),
 dict(id="xifu", name="Western Garrison of Jing", name_zh="荆州西府", kind="military", from_=345, to=404,
      seats=[(112.2, 30.35, "江陵"), (112.14, 32.0, "襄阳"), (114.3, 30.55, "夏口")],
      families="Huan of Qiao", families_zh="谯国桓氏",
      people="Huan Wen, Huan Chong, Huan Xuan", people_zh="桓温、桓冲、桓玄",
      summary="The upstream army at Jiangling rivalled the court; Huan Wen led northern expeditions from it and Huan Xuan briefly seized the throne in 403.",
      summary_zh="坐镇长江上游、与建康分庭抗礼的荆州军府；桓温由此北伐，桓玄于403年篡晋称帝。",
      source="https://zh.wikipedia.org/wiki/桓温"),
 dict(id="daibei", name="Dai-North Nobility", name_zh="代北勋贵", kind="military", from_=386, to=494,
      seats=[(113.3, 40.08, "平城"), (111.83, 40.4, "盛乐")],
      families="Eight Xianbei noble clans (Mu, Lu, He, Lou...)", families_zh="鲜卑勋臣八姓（穆、陆、贺、刘、楼、于、嵇、尉）",
      people="Cui Hao (Han adviser), Mu Chong", people_zh="穆崇、陆俟（汉臣崔浩辅政）",
      summary="Tuoba Xianbei nobles around Pingcheng ruled early Northern Wei; Emperor Xiaowen's move to Luoyang in 494 left them behind.",
      summary_zh="围绕平城的拓跋鲜卑贵族是北魏前期的统治核心；494年孝文帝迁都洛阳，他们失去中心地位。",
      source="https://zh.wikipedia.org/wiki/北魏孝文帝改革"),
 dict(id="shandong", name="Shandong Great Clans", name_zh="山东士族", kind="gentry", from_=300, to=905,
      seats=[(115.9, 37.2, "清河"), (115.5, 38.23, "博陵"), (115.97, 39.48, "范阳"), (114.77, 37.75, "赵郡"),
             (113.38, 34.79, "荥阳"), (112.5, 37.8, "太原")],
      families="Cui of Qinghe and Boling, Lu of Fanyang, Li of Zhao, Zheng of Xingyang, Wang of Taiyuan",
      families_zh="清河崔、博陵崔、范阳卢、赵郡李、荥阳郑、太原王",
      people="Cui Hao, Lu Sidao, Cui Qun, Li Deyu", people_zh="崔浩、卢思道、崔群、李德裕",
      summary="The 'five surnames, seven houses' east of the Taihang mountains: so prestigious that Tang emperors banned their intermarriage, yet still sought them as in-laws; they faded after Huang Chao and the 905 Baima massacre.",
      summary_zh="太行山以东的“五姓七家”，门第之高连唐太宗、唐高宗都要下诏压制、禁其自相婚姻；黄巢之乱与905年白马驿之祸后衰亡。",
      source="https://zh.wikipedia.org/wiki/五姓七家"),
 dict(id="liuzhen", name="Six Garrisons Clique", name_zh="六镇勋贵", kind="military", from_=524, to=577,
      seats=[(110.1, 41.0, "怀朔"), (112.5, 37.8, "晋阳"), (114.35, 36.33, "邺")],
      families="Garrison soldiers of Huaishuo", families_zh="怀朔镇军人",
      people="Gao Huan, Hou Jing, Sima Ziru, Duan Shao", people_zh="高欢、侯景、司马子如、段韶",
      summary="After the Six Garrisons revolt, Gao Huan led the frontier soldiers to Jinyang; they dominated Eastern Wei and Northern Qi.",
      summary_zh="六镇之乱后，高欢率怀朔等镇军人据晋阳，成为东魏、北齐的勋贵集团，与汉人士族矛盾不断。",
      source="https://zh.wikipedia.org/wiki/六镇之乱"),
 dict(id="guanlong", name="Guanlong Aristocracy", name_zh="关陇集团", kind="bloc", from_=534, to=690,
      seats=[(111.45, 41.1, "武川"), (108.9, 34.27, "长安"), (103.85, 35.37, "陇西"), (109.95, 34.8, "冯翊"),
             (105.7, 34.58, "天水")],
      families="Yuwen, Dugu, Yang (Sui), Li (Tang), Zhangsun; also Wei and Du of Jingzhao",
      families_zh="宇文、独孤、杨（隋）、李（唐）、长孙，并吸纳京兆韦、杜等关中郡姓",
      people="Yuwen Tai, Dugu Xin, Yang Jian, Li Yuan, Zhangsun Wuji", people_zh="宇文泰、独孤信、杨坚、李渊、长孙无忌",
      summary="Yuwen Tai fused Wuchuan garrison men with Guanzhong gentry ('Guanzhong-first' policy). This bloc gave rise to Northern Zhou, Sui and Tang; Wu Zetian broke its hold.",
      summary_zh="宇文泰以“关中本位政策”把武川镇军人与关陇豪族结为一体（八柱国、十二大将军），先后建立北周、隋、唐；武则天时期遭到打压而解体。陈寅恪提出此说。",
      source="https://zh.wikipedia.org/wiki/关陇集团"),
 dict(id="guanzhong", name="Guanzhong Clans", name_zh="关中郡姓", kind="gentry", from_=400, to=907,
      seats=[(109.0, 34.2, "京兆"), (111.22, 35.36, "闻喜"), (110.9, 34.92, "解县"), (110.6, 35.4, "汾阴"), (110.08, 34.56, "华阴")],
      families="Wei and Du of Jingzhao; Pei, Liu, Xue of Hedong; Yang of Hongnong",
      families_zh="京兆韦、杜，河东裴、柳、薛，弘农杨",
      people="Pei Ju, Du Ruhui, Wei Zhuang, Liu Zongyuan, Yang Guozhong", people_zh="裴矩、杜如晦、韦庄、柳宗元、杨国忠",
      summary="The great houses west of the passes; the Pei of Wenxi alone gave Tang 17 chief ministers, and 'Wei and Du south of the city are a foot and five from heaven'.",
      summary_zh="关中与河东的大族。闻喜裴氏在唐代出宰相十七人；俗谚“城南韦杜，去天尺五”。",
      source="https://zh.wikipedia.org/wiki/河东裴氏"),
 dict(id="hesuo", name="Three Hebei Garrisons", name_zh="河朔三镇", kind="military", from_=763, to=914,
      seats=[(115.2, 36.3, "魏州"), (114.57, 38.15, "镇州"), (116.4, 39.9, "幽州")],
      families="Weibo, Chengde, Lulong governors", families_zh="魏博、成德、卢龙节度使",
      people="Tian Chengsi, Li Baochen, Li Huaixian, Luo Hong", people_zh="田承嗣、李宝臣、李怀仙、罗弘信",
      summary="Former An Lushan generals kept Hebei as hereditary fiefs after 763, paying no taxes to the court for 150 years.",
      summary_zh="安史降将据河北，世袭节度使、不输贡赋于朝廷，割据约一百五十年。",
      source="https://zh.wikipedia.org/wiki/河朔三镇"),
 dict(id="shatuo", name="Shatuo Clique", name_zh="沙陀集团", kind="military", from_=883, to=951,
      seats=[(112.5, 37.8, "晋阳"), (112.9, 39.07, "代州"), (113.3, 40.08, "云州")],
      families="Shatuo Turks and Daibei soldiers", families_zh="沙陀突厥与代北军人",
      people="Li Keyong, Li Cunxu, Shi Jingtang, Liu Zhiyuan", people_zh="李克用、李存勖、石敬瑭、刘知远",
      summary="From their base at Taiyuan, Shatuo leaders founded three of the Five Dynasties (Later Tang, Jin, Han).",
      summary_zh="以太原为根据地的沙陀军事集团，先后建立后唐、后晋、后汉三个王朝。",
      source="https://zh.wikipedia.org/wiki/沙陀"),
 dict(id="jiangxi", name="Jiangxi Scholar-Officials", name_zh="江西士大夫", kind="gentry", from_=1030, to=1127,
      seats=[(116.35, 27.95, "临川"), (115.0, 27.1, "庐陵"), (116.53, 27.22, "南丰"), (114.55, 29.03, "分宁")],
      families="Southern examination graduates", families_zh="科举出身的南方士人",
      people="Ouyang Xiu, Wang Anshi, Zeng Gong, Huang Tingjian", people_zh="欧阳修、王安石、曾巩、黄庭坚",
      summary="Through the exams, southerners from Jiangxi rose to lead Northern Song letters and politics, ending northern dominance of court.",
      summary_zh="经由科举，江西士人在北宋文坛与政坛崛起，打破了北方人主导朝廷的局面。",
      source="https://zh.wikipedia.org/wiki/唐宋八大家"),
 dict(id="luoshushuo", name="Luo, Shu and Shuo Factions", name_zh="洛蜀朔党", kind="faction", from_=1086, to=1094,
      seats=[(112.45, 34.62, "洛阳"), (103.83, 30.05, "眉山"), (116.53, 37.88, "东光"), (115.15, 36.28, "大名")],
      families="Conservatives split by home region", families_zh="旧党内部按籍贯分裂",
      people="Cheng Yi (Luo), Su Shi (Shu), Liu Zhi (Shuo)", people_zh="程颐（洛党）、苏轼（蜀党）、刘挚（朔党）",
      summary="After the conservatives returned in 1086, they split into three regional factions that quarrelled until the reformers came back in 1094.",
      summary_zh="元祐年间旧党执政后，按籍贯分裂为洛、蜀、朔三党互相攻讦，直到1094年新党复起。",
      source="https://zh.wikipedia.org/wiki/洛蜀党争"),
 dict(id="shihou", name="Han Warlord Marquises", name_zh="汉人世侯", kind="military", from_=1215, to=1263,
      seats=[(114.57, 38.15, "真定"), (115.47, 38.87, "顺天"), (116.3, 35.9, "东平"), (118.48, 36.68, "益都")],
      families="Shi of Zhending, Zhang of Shuntian, Yan of Dongping, Li of Yidu", families_zh="真定史氏、顺天张氏、东平严氏、益都李氏",
      people="Shi Tianze, Zhang Rou, Yan Shi, Li Tan", people_zh="史天泽、张柔、严实、李璮",
      summary="Northern Chinese strongmen who submitted to the Mongols ruled their districts by inheritance; after Li Tan's revolt in 1262 Kublai abolished their hereditary powers.",
      summary_zh="归附蒙古的北方汉人地方武装，世袭统治所据州县；1262年李璮之乱后，忽必烈罢世侯、行迁转。",
      source="https://zh.wikipedia.org/wiki/汉人世侯"),
 dict(id="huaixi", name="Huaixi Clique", name_zh="淮西集团", kind="bloc", from_=1353, to=1393,
      seats=[(117.55, 32.87, "濠州"), (117.68, 32.53, "定远"), (117.2, 32.97, "怀远")],
      families="Zhu Yuanzhang's fellow villagers", families_zh="朱元璋同乡功臣",
      people="Xu Da, Chang Yuchun, Li Shanchang, Tang He, Lan Yu", people_zh="徐达、常遇春、李善长、汤和、蓝玉",
      summary="Generals and ministers from Zhu Yuanzhang's home region founded Ming; the purges of Hu Weiyong (1380) and Lan Yu (1393) destroyed them.",
      summary_zh="朱元璋的淮西同乡构成明朝开国功臣主体；胡惟庸案（1380）与蓝玉案（1393）将其几乎诛尽。",
      source="https://zh.wikipedia.org/wiki/淮西勋贵"),
 dict(id="zhedong", name="Zhedong Clique", name_zh="浙东集团", kind="bloc", from_=1360, to=1375,
      seats=[(120.28, 28.14, "青田"), (119.9, 29.45, "浦江"), (119.13, 28.08, "龙泉"), (119.92, 28.45, "丽水")],
      families="Eastern Zhejiang scholars", families_zh="浙东文士",
      people="Liu Ji, Song Lian, Zhang Yi, Ye Chen", people_zh="刘基、宋濂、章溢、叶琛",
      summary="Scholars recruited in 1360 who shaped early Ming institutions, rivals of the Huaixi generals; Liu Ji died in 1375.",
      summary_zh="1360年受聘的“浙东四先生”，为明初制度建设出力，与淮西集团相争；1375年刘基去世后衰落。",
      source="https://zh.wikipedia.org/wiki/刘基"),
 dict(id="jinshang", name="Shanxi Merchants", name_zh="晋商", kind="merchant", from_=1500, to=1912,
      seats=[(112.17, 37.2, "平遥"), (112.55, 37.42, "太谷"), (112.33, 37.36, "祁县"), (111.85, 37.4, "介休")],
      families="Qiao, Qu, Cao, Fan", families_zh="乔、渠、曹、范诸家",
      people="Lei Lütai (Rishengchang bank)", people_zh="雷履泰（日升昌票号）",
      summary="Rich from supplying the frontier armies and the salt trade, Shanxi merchants later ran China's remittance banks (piaohao).",
      summary_zh="起于为边军输粮换盐引，后经营茶叶、票号，汇通天下。",
      source="https://zh.wikipedia.org/wiki/晋商"),
 dict(id="huishang", name="Huizhou Merchants", name_zh="徽商", kind="merchant", from_=1500, to=1850,
      seats=[(118.43, 29.87, "歙县"), (118.18, 29.78, "休宁"), (117.86, 29.25, "婺源"), (117.93, 29.93, "黟县")],
      families="Wang, Jiang, Bao, Hu", families_zh="汪、江、鲍、胡诸家",
      people="Hu Xueyan (late), Bao Zhidao", people_zh="鲍志道、胡雪岩（晚期）",
      summary="Salt merchants of Yangzhou and patrons of learning; 'no town without Huizhou men'.",
      summary_zh="以扬州盐业为根本，亦贾亦儒，“无徽不成镇”。",
      source="https://zh.wikipedia.org/wiki/徽商"),
 dict(id="donglin", name="Donglin Faction", name_zh="东林党", kind="faction", from_=1604, to=1627,
      seats=[(120.3, 31.57, "无锡"), (119.95, 31.78, "常州"), (120.6, 31.3, "苏州"), (121.2, 31.0, "松江")],
      families="Jiangnan scholar-officials", families_zh="江南士大夫",
      people="Gu Xiancheng, Gao Panlong, Yang Lian, Zuo Guangdou", people_zh="顾宪成、高攀龙、杨涟、左光斗",
      summary="Centred on the Donglin Academy in Wuxi; they fought the eunuch Wei Zhongxian and were purged in 1625–26.",
      summary_zh="以无锡东林书院为中心的江南士大夫，抨击时政，与魏忠贤阉党相斗，1625—1626年遭血腥清洗。",
      source="https://zh.wikipedia.org/wiki/东林党"),
 dict(id="qichuzhe", name="Qi, Chu and Zhe Factions", name_zh="齐楚浙党", kind="faction", from_=1605, to=1627,
      seats=[(121.55, 29.87, "宁波"), (117.65, 36.2, "莱芜"), (114.87, 30.45, "黄冈")],
      families="Officials grouped by home province", families_zh="按籍贯结成的官僚派系",
      people="Shen Yiguan (Zhe), Qi Shijiao (Qi), Guan Yingzhen (Chu)", people_zh="沈一贯（浙党）、亓诗教（齐党）、官应震（楚党）",
      summary="Provincial factions opposed to the Donglin; many later joined Wei Zhongxian's eunuch party.",
      summary_zh="与东林党对立的地域派系，后多依附魏忠贤阉党。",
      source="https://zh.wikipedia.org/wiki/明朝党争"),
 dict(id="liaodong", name="Liaodong Generals", name_zh="辽东将门", kind="military", from_=1570, to=1662,
      seats=[(121.8, 41.6, "广宁"), (120.85, 40.6, "宁远"), (121.12, 41.1, "锦州"), (123.17, 41.27, "辽阳")],
      families="Li, Zu, Wu", families_zh="李氏、祖氏、吴氏",
      people="Li Chengliang, Zu Dashou, Wu Xiang, Wu Sangui", people_zh="李成梁、祖大寿、吴襄、吴三桂",
      summary="Hereditary frontier families who defended Liaodong (the Guan-Ning army); Wu Sangui opened Shanhai Pass to the Qing in 1644.",
      summary_zh="世代镇守辽东的将门（关宁军），1644年吴三桂开山海关引清兵入关。",
      source="https://zh.wikipedia.org/wiki/关宁铁骑"),
 dict(id="xiangjun", name="Hunan Army Clique", name_zh="湘军集团", kind="military", from_=1853, to=1912,
      seats=[(112.5, 27.73, "湘乡"), (112.9, 28.68, "湘阴"), (112.35, 28.55, "益阳"), (112.94, 28.2, "长沙")],
      families="Hunan gentry and their militia", families_zh="湖南士绅与团练",
      people="Zeng Guofan, Zuo Zongtang, Hu Linyi, Zeng Guoquan", people_zh="曾国藩、左宗棠、胡林翼、曾国荃",
      summary="Gentry-led militia that crushed the Taiping; its leaders became governors across the empire, shifting power from Manchus to Han officials.",
      summary_zh="由湖南士绅组建的团练，镇压太平天国后，其首领遍任各省督抚，地方权力由满人转入汉人手中。",
      source="https://zh.wikipedia.org/wiki/湘军"),
 dict(id="huaijun", name="Anhui Army Clique", name_zh="淮军集团", kind="military", from_=1862, to=1912,
      seats=[(117.27, 31.86, "合肥"), (117.15, 31.7, "肥西"), (116.5, 31.75, "六安")],
      families="Anhui militia leaders", families_zh="皖中团练首领",
      people="Li Hongzhang, Liu Mingchuan, Zhang Shusheng", people_zh="李鸿章、刘铭传、张树声",
      summary="Li Hongzhang's army from Hefei succeeded the Hunan army and backed the Self-Strengthening Movement and the Beiyang fleet.",
      summary_zh="李鸿章在合肥一带组建，继湘军之后成为清廷支柱，主导洋务运动与北洋水师。",
      source="https://zh.wikipedia.org/wiki/淮军"),
 dict(id="beiyang", name="Beiyang Clique", name_zh="北洋集团", kind="military", from_=1895, to=1912,
      seats=[(117.4, 38.95, "小站"), (117.2, 39.13, "天津"), (115.47, 38.87, "保定")],
      families="Officers of the New Army", families_zh="新建陆军将领",
      people="Yuan Shikai, Duan Qirui, Feng Guozhang, Wang Shizhen", people_zh="袁世凯、段祺瑞、冯国璋、王士珍",
      summary="Yuan Shikai's modern army trained at Xiaozhan; in 1912 it decided the end of the Qing.",
      summary_zh="袁世凯在天津小站编练的新式陆军，1912年左右了清帝退位与民国初局。",
      source="https://zh.wikipedia.org/wiki/北洋军阀"),
]

R, GAP = 0.5, 3.5  # padding around the seats and the distance that still counts as one region, degrees
out = []
for g in G:
    g = dict(g)
    # Seats within GAP degrees of each other form one region (their hull); distant seats stay separate patches.
    pts = [(x, y) for x, y, _ in g["seats"]]
    groups = []
    for pt in pts:
        near = [c for c in groups if any(math.dist(pt, q) < GAP for q in c)]
        merged = [pt] + [q for c in near for q in c]
        groups = [c for c in groups if c not in near] + [merged]
    blob = unary_union([MultiPoint(c).convex_hull.buffer(R, 24) for c in groups])
    blob = blob.buffer(0.3, 16).buffer(-0.3, 16).simplify(0.02)
    big = max(getattr(blob, "geoms", [blob]), key=lambda q: q.area)
    c = big.representative_point() if not big.contains(big.centroid) else big.centroid
    g["label"] = [round(c.x, 3), round(c.y, 3)]  # label on the largest patch
    geom = mapping(blob)
    polys = [geom["coordinates"]] if geom["type"] == "Polygon" else list(geom["coordinates"])
    polys = [[[[round(x, 3), round(y, 3)] for x, y in ring] for ring in poly] for poly in polys]
    g["from"] = g.pop("from_")
    g["seats"] = [list(s) for s in g["seats"]]
    g["geometry"] = {"type": "MultiPolygon", "coordinates": polys}
    out.append(g)
json.dump(out, open("data/clans.json", "w"), ensure_ascii=False, separators=(",", ":"))
print(len(out), "groups")
